kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:6.7.1-jdk11
    commands:
      - sudo apt-get update
      - sudo apt-get install -y p7zip-full unrar
      - gradle test
  - name: publish
    image: gradle:6.7.1-jdk11
    environment:
      ARTEFACTS_USER:
        from_secret: ARTEFACTS_USER
      ARTEFACTS_PASSWORD:
        from_secret: ARTEFACTS_PASSWORD
    commands:
      - gradle publish execJar
      - ./etc/publish.sh https://code.shrimpworks.za.net/artefacts/unreal-archive ./build/libs/unreal-archive ./build/libs/unreal-archive-exec.jar
      - "export CI_BUILD=$(gradle properties | grep 'version:' | sed 's/version: //') && \
      ./etc/publish.sh https://code.shrimpworks.za.net/artefacts/package-dependency ./build/libs/package-dependency ./build/libs/package-dependency-exec.jar"
    when:
      branch:
        - master
  - name: www
    image: plugins/downstream
    environment:
      DRONE_TOKEN:
        from_secret: DRONE_TOKEN
    commands:
      - ./etc/rebuild-www
    when:
      branch:
        - master
