dist: xenial
language: java

jdk:
  - openjdk11

git:
  submodules: false

before_cache:
  - rm -f  ~/.gradle/caches/modules-2/modules-2.lock
  - rm -fr ~/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - ~/.gradle/caches/
    - ~/.gradle/wrapper/

before_install:
  - sudo apt-get update
  - sudo apt-get install -y p7zip-full unrar

jobs:
  include:
    - stage: test
      script: ./gradlew test
    - stage: build and publish binaries
      if: branch = master
      script:
        - ./gradlew publish execJar
        - ./etc/publish.sh https://code.shrimpworks.za.net/artefacts/unreal-archive ./build/libs/unreal-archive ./build/libs/unreal-archive-exec.jar
        - ./etc/rebuild-www.sh
