language: java
jdk:
  - openjdk8

git:
  submodules: false

before_install:
  - sudo apt-get update
  - sudo apt-get install -y p7zip-full unrar

jobs:
  include:
    - stage: test
      script: ant test
    - stage: build and publish binaries
      if: branch = master
      script:
        - ant bin
        - ./resources/publish.sh https://code.shrimpworks.za.net/artefacts/unreal-archive ./dist/unreal-archive ./dist/unreal-archive-exec.jar
    - stage: trigger publish of www content
      if: branch = master
      script:
        - ./resources/rebuild-www.sh
